spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
server.error.include-stacktrace=never
server.error.include-message=always
spring.devtools.add-properties=false
